### ISSUE TITLE
Error pada saat konversi messageToString

### ISSUE THREAD

**Issue by aanfarhan** [artivisi/iso8583-processor#2]
Saat saya mencoba mengimplementasikan echo test, berhasil mengirim pesan tapi waktu baca balasan dengan memanggil method `messageToString` mendapatkan error seperti ini: `java.lang.StringIndexOutOfBoundsException: String index out of range: 58`
contoh message balasan: `081082200000020000000400000000000000032102524412345600301`

**Comment by sulistionoadi** [comment]
itu dikarenakan anda belum membuat mapper, 
mapper ini digunakan untuk memecah string message menjadi per bit
