### ISSUE TITLE
Mapping LLLCHAR

### ISSUE THREAD

**Issue by aanfarhan** [artivisi/iso8583-processor#3]
Bagaimana cara set mapping untuk LLLCHAR? Saya memakai library iso8583processor-core

**Comment by sulistionoadi** [comment]
contoh menggunakan mapper

`Mapper m = new Mapper();`
`m.getDataElement().put(48, //nomor bit`
                 `new DataElement()`
                 `.setLengthType(DataElementLength.VARIABLE)`
                 `.setLengthPrefix(2)`
                 `.setNumber(48)`
                 `.setType(DataElementType.ALPHANUMERIC)`
`);`

Penjelasan
- setLengthType : untuk mendefinisikan type panjang bit
    - VARIABLE : jika panjang bit bervariasi / menggunakan prefix (LL, LLL)
    - FIXED : jika panjang bit tetap (fixed)
- setLengthPrefix : sesuai spec iso, jika LL maka diisi 2, jika LLL maka diisi 3
- setNumber : untuk mendefinisikan nomor bit
- setType : untuk mendefinisikan tipe karakter yang diperbolehkan
    - ALPHANUMERIC
    - BINARY
    - NUMERIC
